[package]

name = "silver"
version = "0.0.1"
authors = ["Maik Klein <maikklein@googlemail.com>"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
